require('colortheme')
require('options') -- this should be at the top for lualine  
--require('lualine-config')
require('staline-config')   -- use staline or lualine
require('plugins')
require('treesitter-config')
--require('bufferline-config')
require('barbar-config')  -- use bufferline or barbar-config
require('autopair-config')
require('autosave-config')
require('comments-config')
require('keybindings')
require('lsp')
require('motion')
require('nvim-tree-config')
require('smoothscrolling-config')
require('telescope-config')
require('toggleterm-config')
--require('whichkey-config')
require('colorpicker-config')
--require('cphelpher-config')
require('markdownpreview-config')
